
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-demo using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=deposit_d889dac99b
ROOST_METHOD_SIG_HASH=deposit_54d4c8262f

[
  {
    "vulnerability": "CWE-20: Improper Input Validation",
    "issue": "The code only checks if strings are empty but doesn't validate format, range, or malicious content. Numeric parsing occurs without validation, allowing potential NumberFormatException or injection of invalid values like negative deposits.",
    "solution": "Implement comprehensive input validation using regex patterns for account ID format, range checks for deposit amounts (positive values only), and proper exception handling around parsing operations. Use BigDecimal for monetary calculations instead of double."
  },
  {
    "vulnerability": "CWE-89: SQL Injection",
    "issue": "Direct use of parsed integers and doubles in repository methods without parameterized queries could lead to SQL injection if the repository layer doesn't properly sanitize inputs, especially with the acc_id parameter.",
    "solution": "Ensure all repository methods use parameterized queries or prepared statements. Validate that accountRepository methods properly sanitize inputs and use JPA/Hibernate parameter binding instead of string concatenation."
  },
  {
    "vulnerability": "CWE-284: Improper Access Control",
    "issue": "No verification that the account_id belongs to the authenticated user, allowing potential unauthorized access to other users' accounts through account ID manipulation.",
    "solution": "Add authorization check to verify account ownership: validate that the provided account_id belongs to the authenticated user before performing any operations. Implement proper access control at the service layer."
  },
  {
    "vulnerability": "CWE-362: Concurrent Execution Race Condition",
    "issue": "The deposit operation involves multiple non-atomic steps (get balance, calculate new balance, update balance) without transaction management, creating race conditions in concurrent environments that could lead to incorrect balance calculations.",
    "solution": "Wrap the entire deposit operation in a database transaction using @Transactional annotation. Implement optimistic or pessimistic locking mechanisms to prevent concurrent balance modifications."
  },
  {
    "vulnerability": "CWE-476: NULL Pointer Dereference",
    "issue": "No null checks on session.getAttribute('user') result or repository method returns, potentially causing NullPointerException if session expires or database queries fail.",
    "solution": "Add explicit null checks for user object from session and all repository method returns. Implement proper session validation and return appropriate error responses for null scenarios."
  },
  {
    "vulnerability": "CWE-665: Improper Initialization",
    "issue": "Variables like user, user_id, currentBalance, newBalance, and currentDateTime are used without declaration or proper initialization, indicating incomplete code that could lead to compilation errors or runtime exceptions.",
    "solution": "Properly declare all variables with appropriate types and initialize them. Add proper variable scoping and ensure currentDateTime is set using LocalDateTime.now() before use in transaction logging."
  },
  {
    "vulnerability": "CWE-352: Cross-Site Request Forgery",
    "issue": "The POST endpoint lacks CSRF protection, allowing malicious websites to perform unauthorized deposit operations on behalf of authenticated users through cross-site requests.",
    "solution": "Enable Spring Security's CSRF protection and ensure proper CSRF token validation for state-changing operations. Use @RequestMapping with proper method restrictions and implement anti-CSRF tokens."
  },
  {
    "vulnerability": "CWE-704: Incorrect Type Conversion",
    "issue": "Using double for monetary calculations introduces floating-point precision errors that can lead to incorrect financial calculations and potential loss of funds in banking operations.",
    "solution": "Replace double with BigDecimal for all monetary calculations to ensure precise decimal arithmetic. Use appropriate rounding modes and scale settings for financial operations."
  }
]
,Scenario 1: Successful Deposit with Valid Inputs

Details:
  TestName: successfulDepositWithValidInputs
  Description: This test verifies that a deposit operation completes successfully when provided with valid deposit amount and account ID, with a valid user session.

Execution:
  Arrange: Set up mocks for accountRepository and transactRepository. Create a valid HttpSession with a User object containing a valid user_id. Prepare a requestMap with valid deposit_amount and account_id values. Mock the repository methods to return expected values.
  Act: Call the deposit method with the prepared requestMap and session parameters.
  Assert: Verify that the response has HTTP status 200 (OK), contains the success message "Amount Deposited Successfully.", and includes the updated accounts information.

Validation:
  The assertion verifies that the deposit operation executes the complete workflow including balance calculation, account update, and transaction logging. This test ensures the primary happy path functionality works as expected for legitimate deposit requests.

Scenario 2: Bad Request When Deposit Amount is Empty

Details:
  TestName: badRequestWhenDepositAmountIsEmpty
  Description: This test validates that the method returns a bad request response when the deposit_amount field in the request is empty or null.

Execution:
  Arrange: Create a requestMap with an empty string for deposit_amount and a valid account_id. Set up a valid HttpSession with User object.
  Act: Invoke the deposit method with the requestMap containing empty deposit_amount.
  Assert: Verify that the response has HTTP status 400 (Bad Request) and contains the error message "Deposit amount and account ID cannot be empty."

Validation:
  This assertion ensures proper input validation for the deposit amount field. The test confirms that the method properly handles invalid input scenarios and provides appropriate error feedback to prevent processing of incomplete requests.

Scenario 3: Bad Request When Account ID is Empty

Details:
  TestName: badRequestWhenAccountIdIsEmpty
  Description: This test checks that the method returns a bad request response when the account_id field in the request is empty or null.

Execution:
  Arrange: Create a requestMap with a valid deposit_amount and an empty string for account_id. Set up a valid HttpSession with User object.
  Act: Call the deposit method with the requestMap containing empty account_id.
  Assert: Verify that the response has HTTP status 400 (Bad Request) and the response body contains "Deposit amount and account ID cannot be empty."

Validation:
  The assertion validates that account ID field validation works correctly. This test is crucial for ensuring data integrity and preventing operations on undefined accounts.

Scenario 4: Bad Request When Both Fields are Empty

Details:
  TestName: badRequestWhenBothFieldsAreEmpty
  Description: This test verifies that the method handles the case where both deposit_amount and account_id are empty strings in the request.

Execution:
  Arrange: Create a requestMap with empty strings for both deposit_amount and account_id. Set up a valid HttpSession.
  Act: Invoke the deposit method with the requestMap containing both empty fields.
  Assert: Verify that the response returns HTTP status 400 and contains the appropriate error message about empty fields.

Validation:
  This assertion confirms that the validation logic properly handles multiple empty fields simultaneously. The test ensures comprehensive input validation for all required parameters.

Scenario 5: Bad Request When Deposit Amount is Zero

Details:
  TestName: badRequestWhenDepositAmountIsZero
  Description: This test validates that the method rejects deposit requests where the deposit amount is exactly zero.

Execution:
  Arrange: Create a requestMap with deposit_amount as "0" and a valid account_id. Set up HttpSession with a valid User object. Mock the user.getUser_id() method to return a valid user ID string.
  Act: Call the deposit method with the zero deposit amount.
  Assert: Verify that the response has HTTP status 400 and contains the error message "Deposit amount cannot be zero."

Validation:
  The assertion ensures that business logic prevents meaningless zero-value deposits. This test validates that the application enforces reasonable business rules for financial transactions.

Scenario 6: Successful Deposit with Decimal Amount

Details:
  TestName: successfulDepositWithDecimalAmount
  Description: This test verifies that the deposit method correctly handles decimal deposit amounts and performs accurate balance calculations.

Execution:
  Arrange: Set up mocks for repositories. Create requestMap with a decimal deposit_amount like "150.75" and valid account_id. Mock accountRepository.getAccountBalance() to return a current balance. Set up valid HttpSession with User object.
  Act: Execute the deposit method with decimal amount parameters.
  Assert: Verify HTTP status 200, success message, and that the balance calculation includes the decimal precision correctly.

Validation:
  This assertion confirms that the method handles monetary calculations with proper decimal precision. The test is important for ensuring accurate financial computations in real-world scenarios.

Scenario 7: Successful Deposit Updates Account Balance

Details:
  TestName: successfulDepositUpdatesAccountBalance
  Description: This test validates that a successful deposit operation correctly updates the account balance by calling the appropriate repository method.

Execution:
  Arrange: Mock accountRepository methods. Set currentBalance to 1000.0 via getAccountBalance mock. Create requestMap with deposit_amount "500.0" and valid account_id. Set up valid session.
  Act: Call the deposit method and capture the repository interactions.
  Assert: Verify that changeAccountsBalanceById was called with the correct new balance (1500.0) and account ID.

Validation:
  The assertion verifies that balance updates are performed correctly with accurate calculations. This test ensures the core financial operation logic works as intended.

Scenario 8: Successful Deposit Logs Transaction

Details:
  TestName: successfulDepositLogsTransaction
  Description: This test checks that a successful deposit operation creates a proper transaction log entry with all required details.

Execution:
  Arrange: Set up repository mocks including transactRepository.logTransaction(). Create valid requestMap and HttpSession. Mock other dependencies to allow successful flow.
  Act: Execute the deposit method with valid parameters.
  Assert: Verify that logTransaction was called with correct parameters including account ID, "deposit" type, amount, "online" method, "success" status, success message, and currentDateTime.

Validation:
  This assertion ensures proper audit trail creation for financial transactions. The test validates that all deposit operations are properly recorded for compliance and tracking purposes.

Scenario 9: Number Format Exception When Account ID is Invalid

Details:
  TestName: numberFormatExceptionWhenAccountIdIsInvalid
  Description: This test verifies the behavior when account_id contains non-numeric characters that cannot be parsed to integer.

Execution:
  Arrange: Create requestMap with valid deposit_amount and account_id containing non-numeric value like "abc123". Set up valid HttpSession.
  Act: Call the deposit method with invalid account_id format.
  Assert: Verify that a NumberFormatException is thrown or handled appropriately by the application.

Validation:
  The assertion checks error handling for invalid data format scenarios. This test ensures the application gracefully handles or appropriately fails when receiving malformed input data.

Scenario 10: Number Format Exception When Deposit Amount is Invalid

Details:
  TestName: numberFormatExceptionWhenDepositAmountIsInvalid
  Description: This test validates the behavior when deposit_amount contains non-numeric characters that cannot be parsed to double.

Execution:
  Arrange: Create requestMap with deposit_amount containing invalid format like "invalid_amount" and valid account_id. Set up valid HttpSession with User object.
  Act: Invoke the deposit method with invalid deposit_amount format.
  Assert: Verify that a NumberFormatException is thrown or handled appropriately.

Validation:
  This assertion ensures proper handling of invalid numeric input for monetary values. The test is critical for preventing application crashes due to malformed financial data.

Scenario 11: Null Pointer Exception When User Session is Invalid

Details:
  TestName: nullPointerExceptionWhenUserSessionIsInvalid
  Description: This test checks the behavior when the HttpSession does not contain a valid User object or the session is null.

Execution:
  Arrange: Create valid requestMap with proper deposit_amount and account_id. Set up HttpSession that returns null for getAttribute("user") or use null session.
  Act: Call the deposit method with invalid session state.
  Assert: Verify that a NullPointerException is thrown or handled appropriately when trying to access user.getUser_id().

Validation:
  The assertion validates session management and user authentication requirements. This test ensures the application properly handles unauthenticated or expired session scenarios.

Scenario 12: Successful Deposit Returns User Accounts

Details:
  TestName: successfulDepositReturnsUserAccounts
  Description: This test verifies that a successful deposit operation includes the updated user accounts information in the response.

Execution:
  Arrange: Mock accountRepository.getUserAccountsById() to return a list of user accounts. Set up all other mocks for successful deposit flow. Create valid requestMap and HttpSession.
  Act: Execute the deposit method with valid parameters.
  Assert: Verify that the response contains "accounts" key with the user accounts data returned from getUserAccountsById method.

Validation:
  This assertion ensures that clients receive updated account information after deposit operations. The test validates that the response provides complete information needed for UI updates or further operations.


roost_feedback [26/03/2026, 6:56:05 AM]:-\sAdd\smore\scomments\sto\sthe\stest
*/

// ********RoostGPT********

package com.beko.DemoBank_v1.controllers;

import com.beko.DemoBank_v1.models.User;
import com.beko.DemoBank_v1.repository.AccountRepository;
import com.beko.DemoBank_v1.repository.TransactRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import javax.servlet.http.HttpSession;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import com.beko.DemoBank_v1.models.PaymentRequest;
import com.beko.DemoBank_v1.models.TransferRequest;
import com.beko.DemoBank_v1.repository.PaymentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import javax.servlet.http.HttpServletRequest;

@ExtendWith(MockitoExtension.class)
class TransactControllerDepositTest {

	@Mock
	private AccountRepository accountRepository;

	@Mock
	private TransactRepository transactRepository;

	@Mock
	private HttpSession session;

	@Mock
	private User user;

	@InjectMocks
	private TransactController transactController;

	private Map<String, String> requestMap;

	@BeforeEach
	void setUp() {
		// Initialize the request map before each test to ensure clean state
		requestMap = new HashMap<>();
	}

	@Test
	@Tag("valid")
	void successfulDepositWithValidInputs() {
		// Test scenario: Valid deposit operation with proper amount and account ID
		// This test verifies that a successful deposit updates the account balance,
		// logs the transaction, and returns the correct response format
		
		// Arrange - Setup test data with valid deposit amount and account ID
		requestMap.put("deposit_amount", "500.0");
		requestMap.put("account_id", "1");

		// Mock user session and account operations
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("123");
		when(accountRepository.getAccountBalance(123, 1)).thenReturn(1000.0);
		when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

		// Act - Execute the deposit operation
		ResponseEntity<?> response = transactController.deposit(requestMap, session);

		// Assert - Verify successful response and proper system behavior
		assertEquals(HttpStatus.OK, response.getStatusCode());
		assertNotNull(response.getBody());

		// Verify response body contains expected success message and accounts
		Map<String, Object> responseBody = (Map<String, Object>) response.getBody();
		assertEquals("Amount Deposited Successfully.", responseBody.get("message"));
		assertNotNull(responseBody.get("accounts"));

		// Verify account balance was updated correctly (1000 + 500 = 1500)
		verify(accountRepository).changeAccountsBalanceById(1500.0, 1);
		// Verify transaction was logged with correct parameters
		verify(transactRepository).logTransaction(eq(1), eq("deposit"), eq(500.0), eq("online"), eq("success"),
				eq("Deposit Transaction Successfull"), any(LocalDateTime.class));
	}

	@Test
	@Tag("invalid")
	void badRequestWhenDepositAmountIsEmpty() {
		// Test scenario: Invalid input with empty deposit amount
		// Verifies that the system properly handles and rejects empty deposit amounts
		
		// Arrange - Setup request with empty deposit amount but valid account ID
		requestMap.put("deposit_amount", "");
		requestMap.put("account_id", "1");

		// Act - Attempt deposit with invalid input
		ResponseEntity<?> response = transactController.deposit(requestMap, session);

		// Assert - Verify proper error handling with BAD_REQUEST status
		assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
		assertEquals("Deposit amount and account ID cannot be empty.", response.getBody());
	}

	@Test
	@Tag("invalid")
	void badRequestWhenAccountIdIsEmpty() {
		// Test scenario: Invalid input with empty account ID
		// Ensures the system rejects requests with missing account identification
		
		// Arrange - Setup request with valid deposit amount but empty account ID
		requestMap.put("deposit_amount", "500.0");
		requestMap.put("account_id", "");

		// Act - Attempt deposit with missing account ID
		ResponseEntity<?> response = transactController.deposit(requestMap, session);

		// Assert - Verify rejection of invalid request
		assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
		assertEquals("Deposit amount and account ID cannot be empty.", response.getBody());
	}

	@Test
	@Tag("invalid")
	void badRequestWhenBothFieldsAreEmpty() {
		// Test scenario: Complete invalid input with both required fields empty
		// Validates comprehensive input validation for deposit requests
		
		// Arrange - Setup request with both required fields empty
		requestMap.put("deposit_amount", "");
		requestMap.put("account_id", "");

		// Act - Attempt deposit with completely invalid input
		ResponseEntity<?> response = transactController.deposit(requestMap, session);

		// Assert - Verify proper error response for missing data
		assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
		assertEquals("Deposit amount and account ID cannot be empty.", response.getBody());
	}

	@Test
	@Tag("boundary")
	void badRequestWhenDepositAmountIsZero() {
		// Test scenario: Boundary case testing with zero deposit amount
		// Ensures business rule that deposits must be greater than zero
		
		// Arrange - Setup request with zero amount (boundary case)
		requestMap.put("deposit_amount", "0");
		requestMap.put("account_id", "1");

		// Mock user session for authentication
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("123");

		// Act - Attempt zero-amount deposit
		ResponseEntity<?> response = transactController.deposit(requestMap, session);

		// Assert - Verify rejection of zero-amount deposits
		assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
		assertEquals("Deposit amount cannot be zero.", response.getBody());
	}

	@Test
	@Tag("valid")
	void successfulDepositWithDecimalAmount() {
		// Test scenario: Valid deposit with decimal amount
		// Verifies system correctly handles and processes decimal currency values
		
		// Arrange - Setup request with decimal deposit amount
		requestMap.put("deposit_amount", "150.75");
		requestMap.put("account_id", "2");

		// Mock user session and account data for different user/account
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("456");
		when(accountRepository.getAccountBalance(456, 2)).thenReturn(1000.0);
		when(accountRepository.getUserAccountsById(456)).thenReturn(List.of());

		// Act - Execute deposit with decimal amount
		ResponseEntity<?> response = transactController.deposit(requestMap, session);

		// Assert - Verify successful processing of decimal amounts
		assertEquals(HttpStatus.OK, response.getStatusCode());

		Map<String, Object> responseBody = (Map<String, Object>) response.getBody();
		assertEquals("Amount Deposited Successfully.", responseBody.get("message"));

		// Verify correct decimal calculation (1000.0 + 150.75 = 1150.75)
		verify(accountRepository).changeAccountsBalanceById(1150.75, 2);
		verify(transactRepository).logTransaction(eq(2), eq("deposit"), eq(150.75), eq("online"), eq("success"),
				eq("Deposit Transaction Successfull"), any(LocalDateTime.class));
	}

	@Test
	@Tag("integration")
	void successfulDepositUpdatesAccountBalance() {
		// Test scenario: Integration test focusing on account balance update
		// Verifies that the deposit operation correctly integrates with account repository
		
		// Arrange - Setup standard deposit scenario
		requestMap.put("deposit_amount", "500.0");
		requestMap.put("account_id", "1");

		// Mock all necessary dependencies
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("123");
		when(accountRepository.getAccountBalance(123, 1)).thenReturn(1000.0);
		when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

		// Act - Execute deposit operation
		transactController.deposit(requestMap, session);

		// Assert - Focus on account balance integration
		// Verify balance was updated with correct new amount
		verify(accountRepository).changeAccountsBalanceById(1500.0, 1);
		// Verify current balance was retrieved before update
		verify(accountRepository).getAccountBalance(123, 1);
	}

	@Test
	@Tag("integration")
	void successfulDepositLogsTransaction() {
		// Test scenario: Integration test focusing on transaction logging
		// Ensures deposit operations are properly recorded in transaction history
		
		// Arrange - Setup deposit scenario with different amount and account
		requestMap.put("deposit_amount", "300.0");
		requestMap.put("account_id", "3");

		// Mock dependencies with different test data
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("789");
		when(accountRepository.getAccountBalance(789, 3)).thenReturn(500.0);
		when(accountRepository.getUserAccountsById(789)).thenReturn(List.of());

		// Act - Execute deposit operation
		transactController.deposit(requestMap, session);

		// Assert - Focus on transaction logging integration
		// Verify transaction was logged with all correct parameters
		verify(transactRepository).logTransaction(eq(3), eq("deposit"), eq(300.0), eq("online"), eq("success"),
				eq("Deposit Transaction Successfull"), any(LocalDateTime.class));
	}

	@Test
	@Tag("invalid")
	void numberFormatExceptionWhenAccountIdIsInvalid() {
		// Test scenario: Error handling for invalid account ID format
		// Verifies system behavior when non-numeric account ID is provided
		
		// Arrange - Setup request with invalid account ID format
		requestMap.put("deposit_amount", "500.0");
		requestMap.put("account_id", "abc123"); // Invalid non-numeric ID

		// Mock user session
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("123");

		// Act & Assert - Verify NumberFormatException is thrown
		// This tests the system's input validation and error handling
		assertThrows(NumberFormatException.class, () -> {
			transactController.deposit(requestMap, session);
		});
	}

	@Test
	@Tag("invalid")
	void numberFormatExceptionWhenDepositAmountIsInvalid() {
		// Test scenario: Error handling for invalid deposit amount format
		// Ensures proper exception handling when non-numeric amounts are provided
		
		// Arrange - Setup request with invalid deposit amount format
		requestMap.put("deposit_amount", "invalid_amount"); // Invalid non-numeric amount
		requestMap.put("account_id", "1");

		// Mock user session
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("123");

		// Act & Assert - Verify NumberFormatException for invalid amount
		// Tests numeric validation for deposit amounts
		assertThrows(NumberFormatException.class, () -> {
			transactController.deposit(requestMap, session);
		});
	}

	@Test
	@Tag("invalid")
	void nullPointerExceptionWhenUserSessionIsInvalid() {
		// Test scenario: Error handling for invalid user session
		// Verifies system behavior when user is not properly authenticated
		
		// Arrange - Setup request with valid data but invalid session
		requestMap.put("deposit_amount", "500.0");
		requestMap.put("account_id", "1");

		// Mock null user session (unauthenticated user)
		when(session.getAttribute("user")).thenReturn(null);

		// Act & Assert - Verify NullPointerException for invalid session
		// This tests authentication validation in the deposit process
		assertThrows(NullPointerException.class, () -> {
			transactController.deposit(requestMap, session);
		});
	}

	@Test
	@Tag("integration")
	void successfulDepositReturnsUserAccounts() {
		// Test scenario: Integration test for account data retrieval
		// Verifies that deposit response includes updated user account information
		
		// Arrange - Setup deposit with mock account data
		requestMap.put("deposit_amount", "750.0");
		requestMap.put("account_id", "4");

		// Create mock accounts list to verify return data
		List mockAccounts = List.of("Account1", "Account2");

		// Mock all dependencies with test data
		when(session.getAttribute("user")).thenReturn(user);
		when(user.getUser_id()).thenReturn("999");
		when(accountRepository.getAccountBalance(999, 4)).thenReturn(2000.0);
		when(accountRepository.getUserAccountsById(999)).thenReturn(mockAccounts);

		// Act - Execute deposit operation
		ResponseEntity<?> response = transactController.deposit(requestMap, session);

		// Assert - Verify response includes user accounts
		assertEquals(HttpStatus.OK, response.getStatusCode());

		// Verify accounts are included in response body
		Map<String, Object> responseBody = (Map<String, Object>) response.getBody();
		assertEquals(mockAccounts, responseBody.get("accounts"));

		// Verify account data was retrieved
		verify(accountRepository).getUserAccountsById(999);
	}

}
