
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-demo using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-20250514-v1:0

ROOST_METHOD_HASH=transfer_1f3029f5d2
ROOST_METHOD_SIG_HASH=transfer_89d8d3e845

[
  {
    "vulnerability": "CWE-862: Missing Authorization",
    "issue": "The method lacks proper authentication and authorization checks. Any user with a valid session can potentially perform transfers from any account by manipulating the account_id parameter, leading to unauthorized financial transactions.",
    "solution": "Implement proper authorization by verifying that the authenticated user owns the account they are trying to transfer from. Add checks like: if (!accountRepository.isAccountOwnedByUser(user_id, accountID)) { return ResponseEntity.status(HttpStatus.FORBIDDEN).body(\"Unauthorized access to account\"); }"
  },
  {
    "vulnerability": "CWE-209: Information Exposure Through Error Messages",
    "issue": "Error messages reveal sensitive business logic and internal system information such as 'insufficient funds' which can be used by attackers to enumerate valid accounts and understand system behavior.",
    "solution": "Use generic error messages for security-sensitive operations and log detailed information server-side only. Replace specific messages with generic ones like 'Transaction failed' and use structured logging for internal debugging."
  },
  {
    "vulnerability": "CWE-362: Race Condition",
    "issue": "The balance check and update operations are not atomic, creating a race condition where multiple concurrent requests could result in overdrafts or inconsistent account states in a multi-threaded environment.",
    "solution": "Implement database transactions with appropriate isolation levels or use pessimistic locking: @Transactional(isolation = Isolation.SERIALIZABLE) and SELECT ... FOR UPDATE when checking balances to ensure atomic operations."
  },
  {
    "vulnerability": "CWE-20: Improper Input Validation",
    "issue": "Input validation is insufficient - only checks for empty strings but doesn't validate format, length, or sanitize inputs. Numeric parsing can throw uncaught exceptions, and no validation exists for account number format or beneficiary name.",
    "solution": "Implement comprehensive input validation using javax.validation annotations, regex patterns for account numbers, length limits for strings, and proper exception handling for numeric parsing with try-catch blocks around Integer.parseInt() and Double.parseDouble()."
  },
  {
    "vulnerability": "CWE-476: NULL Pointer Dereference",
    "issue": "The code assumes session.getAttribute('user') will never return null and doesn't handle cases where the session is invalid or expired, potentially causing NullPointerException when accessing user properties.",
    "solution": "Add null checks for session attributes: User user = (User) session.getAttribute('user'); if (user == null) { return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body('Session expired'); } before accessing user properties."
  },
  {
    "vulnerability": "CWE-134: Uncontrolled Format String",
    "issue": "Variables like currentDateTime are used but never declared or initialized in the visible code scope, which could lead to compilation errors or runtime exceptions when the method executes.",
    "solution": "Properly declare and initialize all variables: LocalDateTime currentDateTime = LocalDateTime.now(); and ensure all required repository fields are properly autowired and initialized."
  },
  {
    "vulnerability": "CWE-307: Improper Restriction of Excessive Authentication Attempts",
    "issue": "No rate limiting or attempt monitoring is implemented for payment operations, allowing potential brute force attacks or denial of service through excessive payment requests.",
    "solution": "Implement rate limiting using Spring Security or custom interceptors with Redis/cache-based counters to limit payment attempts per user per time window and add CAPTCHA for suspicious activity patterns."
  },
  {
    "vulnerability": "CWE-778: Insufficient Logging",
    "issue": "While transaction logging exists, there's insufficient security event logging for failed authorization attempts, suspicious activities, or input validation failures that could help detect attacks.",
    "solution": "Add comprehensive security logging using a structured logging framework like Logback with appropriate log levels: log.warn('Failed payment attempt for user {} on account {}', user_id, accountID) for security monitoring and incident response."
  }
]
,Scenario 1: Valid Payment Request with Sufficient Funds

Details:
  TestName: validPaymentRequestWithSufficientFunds
  Description: This test verifies that a valid payment request with all required fields populated and sufficient account balance processes successfully and returns a success response with updated account information.

Execution:
  Arrange: Create a PaymentRequest object with valid beneficiary, account number, account ID, reference, and payment amount. Mock HttpSession with a valid User object. Mock AccountRepository to return sufficient balance. Mock PaymentRepository and TransactRepository for logging operations.
  Act: Call the transfer method with the valid PaymentRequest and mocked HttpSession.
  Assert: Verify that ResponseEntity returns HTTP 200 OK status, response body contains success message "Payment Processed Successfully!", and response includes updated accounts information.

Validation:
  This assertion verifies that the payment processing workflow completes successfully when all validation criteria are met. The test ensures that the business logic correctly processes valid payments, updates account balances, logs successful transactions, and returns appropriate success feedback to the user.

Scenario 2: Empty Beneficiary Field

Details:
  TestName: emptyBeneficiaryField
  Description: This test ensures that the system properly validates the beneficiary field and returns a bad request error when the beneficiary field is empty or null.

Execution:
  Arrange: Create a PaymentRequest object with an empty beneficiary field but valid values for other required fields (account_number, account_id, payment_amount). Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing empty beneficiary and mocked HttpSession.
  Assert: Verify that ResponseEntity returns HTTP 400 Bad Request status and response body contains the error message "Beneficiary, account number, account paying from and account payment amount cannot be empty."

Validation:
  This assertion confirms that the input validation logic correctly identifies missing required fields and prevents processing of incomplete payment requests. This is crucial for data integrity and prevents invalid payment transactions from being processed.

Scenario 3: Empty Account Number Field

Details:
  TestName: emptyAccountNumberField
  Description: This test verifies that the system validates the account number field and rejects payment requests when the account number is empty.

Execution:
  Arrange: Create a PaymentRequest object with an empty account_number field but valid values for beneficiary, account_id, and payment_amount. Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing empty account number and mocked HttpSession.
  Assert: Verify that ResponseEntity returns HTTP 400 Bad Request status and response body contains the validation error message about empty required fields.

Validation:
  This test ensures that the account number validation prevents payments to invalid or unspecified accounts, maintaining transaction security and data integrity within the banking system.

Scenario 4: Empty Account ID Field

Details:
  TestName: emptyAccountIdField
  Description: This test checks that the system properly validates the account_id field and returns an appropriate error response when the paying account ID is not provided.

Execution:
  Arrange: Create a PaymentRequest object with an empty account_id field but valid beneficiary, account_number, and payment_amount values. Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing empty account ID and mocked HttpSession.
  Assert: Verify that ResponseEntity returns HTTP 400 Bad Request status and response body contains the field validation error message.

Validation:
  This assertion validates that the system correctly identifies when the source account for payment is not specified, preventing ambiguous payment processing and ensuring proper account identification for all transactions.

Scenario 5: Empty Payment Amount Field

Details:
  TestName: emptyPaymentAmountField
  Description: This test ensures that the system validates the payment_amount field and rejects requests when no payment amount is specified.

Execution:
  Arrange: Create a PaymentRequest object with an empty payment_amount field but valid beneficiary, account_number, and account_id values. Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing empty payment amount and mocked HttpSession.
  Assert: Verify that ResponseEntity returns HTTP 400 Bad Request status and response body contains the validation error message for empty required fields.

Validation:
  This test confirms that payment amount validation prevents processing of payments without specified amounts, which is essential for financial transaction integrity and preventing unintended zero-value or undefined payment processing.

Scenario 6: Zero Payment Amount

Details:
  TestName: zeroPaymentAmount
  Description: This test verifies that the system correctly rejects payment requests when the payment amount is explicitly set to zero, even if all other fields are valid.

Execution:
  Arrange: Create a PaymentRequest object with valid beneficiary, account_number, and account_id, but set payment_amount to "0". Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing zero payment amount and mocked HttpSession.
  Assert: Verify that ResponseEntity returns HTTP 400 Bad Request status and response body contains the specific error message "Payment amount cannot be 0."

Validation:
  This assertion ensures that the business logic prevents zero-value payments, which could be meaningless transactions or potential system abuse. The test validates that the system enforces minimum payment amount requirements.

Scenario 7: Insufficient Funds for Payment

Details:
  TestName: insufficientFundsForPayment
  Description: This test verifies that the system correctly handles payment requests when the account balance is insufficient to cover the requested payment amount.

Execution:
  Arrange: Create a valid PaymentRequest object with all required fields. Mock HttpSession with a valid User object. Mock AccountRepository.getAccountBalance to return a balance lower than the requested payment amount. Mock PaymentRepository.makePayment and TransactRepository.logTransaction for failed transaction logging.
  Act: Call the transfer method with the valid PaymentRequest but insufficient account balance scenario.
  Assert: Verify that ResponseEntity returns HTTP 400 Bad Request status and response body contains "You have insufficient Funds to perform this payment." Also verify that failed payment and transaction logs are created.

Validation:
  This test ensures that the system properly enforces account balance constraints and prevents overdraft situations. It also validates that failed transactions are properly logged for audit purposes and appropriate error messages are returned to users.

Scenario 8: Invalid Account ID Format

Details:
  TestName: invalidAccountIdFormat
  Description: This test checks how the system handles payment requests when the account_id field contains non-numeric values that cannot be parsed to an integer.

Execution:
  Arrange: Create a PaymentRequest object with valid beneficiary, account_number, and payment_amount, but set account_id to a non-numeric string like "abc123". Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing invalid account ID format and mocked HttpSession.
  Assert: Verify that a NumberFormatException is thrown during Integer.parseInt(account_id) operation.

Validation:
  This test validates that the system properly handles data type conversion errors and ensures that only valid numeric account IDs are processed. This is important for preventing system errors and maintaining data type integrity.

Scenario 9: Invalid Payment Amount Format

Details:
  TestName: invalidPaymentAmountFormat
  Description: This test verifies the system's behavior when the payment_amount field contains non-numeric values that cannot be parsed to a double.

Execution:
  Arrange: Create a PaymentRequest object with valid beneficiary, account_number, and account_id, but set payment_amount to a non-numeric string like "invalid_amount". Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing invalid payment amount format and mocked HttpSession.
  Assert: Verify that a NumberFormatException is thrown during Double.parseDouble(payment_amount) operation.

Validation:
  This assertion ensures that the system correctly handles numeric conversion errors for payment amounts and prevents processing of payments with invalid amount formats. This is crucial for financial data integrity.

Scenario 10: Null HttpSession

Details:
  TestName: nullHttpSession
  Description: This test checks the system's behavior when a null HttpSession is passed to the transfer method, simulating scenarios where session management fails.

Execution:
  Arrange: Create a valid PaymentRequest object with all required fields properly populated. Pass null as the HttpSession parameter instead of a mocked session object.
  Act: Call the transfer method with the valid PaymentRequest but null HttpSession.
  Assert: Verify that a NullPointerException is thrown when attempting to access session.getAttribute("user").

Validation:
  This test validates that the system properly handles session management failures and ensures that user authentication is enforced for payment operations. It helps identify potential security vulnerabilities related to session handling.

Scenario 11: Null User in Session

Details:
  TestName: nullUserInSession
  Description: This test verifies the system's behavior when the HttpSession exists but does not contain a valid User object, simulating expired or invalid sessions.

Execution:
  Arrange: Create a valid PaymentRequest object with all required fields. Mock HttpSession to return null when getAttribute("user") is called.
  Act: Call the transfer method with the valid PaymentRequest and mocked HttpSession containing null user.
  Assert: Verify that a NullPointerException is thrown when attempting to access user.getUser_id().

Validation:
  This assertion ensures that the system enforces proper user authentication and prevents payment processing for unauthenticated users. This is essential for security and preventing unauthorized transactions.

Scenario 12: Successful Payment with Reference Field

Details:
  TestName: successfulPaymentWithReferenceField
  Description: This test verifies that payments process correctly when all fields including the optional reference field are provided and the account has sufficient funds.

Execution:
  Arrange: Create a PaymentRequest object with valid values for all fields including a reference description. Mock HttpSession with a valid User object. Mock AccountRepository to return sufficient balance greater than payment amount. Mock PaymentRepository and TransactRepository for successful transaction logging.
  Act: Call the transfer method with the complete PaymentRequest and mocked dependencies.
  Assert: Verify that ResponseEntity returns HTTP 200 OK status, success message is returned, and verify that PaymentRepository.makePayment is called with the reference field value.

Validation:
  This test confirms that the reference field is properly handled and passed through to the payment logging system, ensuring that payment descriptions and references are maintained for record-keeping purposes.

Scenario 13: Large Payment Amount Within Balance Limits

Details:
  TestName: largePaymentAmountWithinBalanceLimits
  Description: This test verifies that the system correctly processes large payment amounts when the account balance is sufficient to cover the transaction.

Execution:
  Arrange: Create a PaymentRequest object with a large payment amount (e.g., "999999.99"). Mock HttpSession with a valid User object. Mock AccountRepository to return an account balance greater than the large payment amount. Mock payment and transaction repositories for logging operations.
  Act: Call the transfer method with the PaymentRequest containing large payment amount and mocked dependencies.
  Assert: Verify that ResponseEntity returns HTTP 200 OK status, success message is returned, and account balance is correctly updated by subtracting the large payment amount.

Validation:
  This test ensures that the system can handle large financial transactions correctly without overflow errors and that the balance calculation logic works properly for significant amounts. This is important for high-value banking operations.

Scenario 14: Multiple Empty Fields Combination

Details:
  TestName: multipleEmptyFieldsCombination
  Description: This test checks the system's validation behavior when multiple required fields are empty simultaneously.

Execution:
  Arrange: Create a PaymentRequest object with empty values for beneficiary, account_number, and payment_amount fields, but provide a valid account_id. Mock HttpSession with a valid User object.
  Act: Call the transfer method with the PaymentRequest containing multiple empty fields and mocked HttpSession.
  Assert: Verify that ResponseEntity returns HTTP 400 Bad Request status and response body contains the validation error message about empty required fields.

Validation:
  This assertion confirms that the validation logic correctly identifies multiple missing fields and provides appropriate error feedback. This ensures comprehensive input validation regardless of which combination of fields are missing.

Scenario 15: Edge Case - Payment Amount Exactly Equal to Balance

Details:
  TestName: paymentAmountExactlyEqualToBalance
  Description: This test verifies the system's behavior when the payment amount exactly matches the available account balance.

Execution:
  Arrange: Create a PaymentRequest object with valid fields and set payment amount to exactly match the account balance. Mock HttpSession with a valid User object. Mock AccountRepository to return an account balance that exactly equals the payment amount. Mock payment and transaction repositories.
  Act: Call the transfer method with the PaymentRequest where payment amount equals available balance.
  Assert: Verify that ResponseEntity returns HTTP 200 OK status, payment processes successfully, and the resulting account balance becomes zero after the transaction.

Validation:
  This test validates that the system correctly handles boundary conditions where payments consume the entire available balance. It ensures that the comparison logic (currentBalance < paymentAmount) works correctly for edge cases and that account balances can be reduced to zero through valid transactions.

*/

// ********RoostGPT********

package com.beko.DemoBank_v1.controllers;

import com.beko.DemoBank_v1.models.PaymentRequest;
import com.beko.DemoBank_v1.models.User;
import com.beko.DemoBank_v1.repository.AccountRepository;
import com.beko.DemoBank_v1.repository.PaymentRepository;
import com.beko.DemoBank_v1.repository.TransactRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import javax.servlet.http.HttpSession;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import com.beko.DemoBank_v1.models.TransferRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;

@ExtendWith(MockitoExtension.class)
class TransactControllerTransfer744Test {

	@Mock
	private AccountRepository accountRepository;

	@Mock
	private PaymentRepository paymentRepository;

	@Mock
	private TransactRepository transactRepository;

	@Mock
	private HttpSession session;

	@InjectMocks
	private TransactController transactController;

	private User mockUser;

	private PaymentRequest paymentRequest;

	@BeforeEach
	void setUp() {
		mockUser = new User();
		mockUser.setUser_id("123");

		paymentRequest = new PaymentRequest();
		paymentRequest.setBeneficiary("John Doe");
		paymentRequest.setAccount_number("9876543210");
		paymentRequest.setAccount_id("1");
		paymentRequest.setReference("Test payment");
		paymentRequest.setPayment_amount("100.50");
	}

	@Test
    @Tag("valid")
    void validPaymentRequestWithSufficientFunds() {
        when(session.getAttribute("user")).thenReturn(mockUser);
        when(accountRepository.getAccountBalance(123, 1)).thenReturn(500.0);
        when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

        ResponseEntity result = transactController.transfer(paymentRequest, session);

        assertEquals(HttpStatus.OK, result.getStatusCode());
        assertTrue(result.getBody() instanceof Map);
        Map<String, Object> response = (Map<String, Object>) result.getBody();
        assertEquals("Payment Processed Successfully!", response.get("message"));
        assertNotNull(response.get("accounts"));

        verify(accountRepository).changeAccountsBalanceById(399.5, 1);
        verify(paymentRepository).makePayment(eq(1), eq("John Doe"), eq("9876543210"),
            eq(100.5), eq("Test payment"), eq("success"), eq("Payment Processed Successfully!"), any(LocalDateTime.class));
        verify(transactRepository).logTransaction(eq(1), eq("Payment"), eq(100.5),
            eq("online"), eq("success"), eq("Payment Transaction Successfull"), any(LocalDateTime.class));
    }

	@Test
	@Tag("invalid")
	void emptyBeneficiaryField() {
		paymentRequest.setBeneficiary("");

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
		assertEquals("Beneficiary, account number, account paying from and account payment amount cannot be empty.",
				result.getBody());
	}

	@Test
	@Tag("invalid")
	void emptyAccountNumberField() {
		paymentRequest.setAccount_number("");

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
		assertEquals("Beneficiary, account number, account paying from and account payment amount cannot be empty.",
				result.getBody());
	}

	@Test
	@Tag("invalid")
	void emptyAccountIdField() {
		paymentRequest.setAccount_id("");

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
		assertEquals("Beneficiary, account number, account paying from and account payment amount cannot be empty.",
				result.getBody());
	}

	@Test
	@Tag("invalid")
	void emptyPaymentAmountField() {
		paymentRequest.setPayment_amount("");

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
		assertEquals("Beneficiary, account number, account paying from and account payment amount cannot be empty.",
				result.getBody());
	}

	@Test
	@Tag("invalid")
	void zeroPaymentAmount() {
		paymentRequest.setPayment_amount("0");

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
		assertEquals("Payment amount cannot be 0.", result.getBody());
	}

	@Test
    @Tag("invalid")
    void insufficientFundsForPayment() {
        when(session.getAttribute("user")).thenReturn(mockUser);
        when(accountRepository.getAccountBalance(123, 1)).thenReturn(50.0);

        ResponseEntity result = transactController.transfer(paymentRequest, session);

        assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
        assertEquals("You have insufficient Funds to perform this payment.", result.getBody());

        verify(paymentRepository).makePayment(eq(1), eq("John Doe"), eq("9876543210"),
            eq(100.5), eq("Test payment"), eq("failed"),
            eq("Coult not Processed Payment due to insufficient funds."), any(LocalDateTime.class));
        verify(transactRepository).logTransaction(eq(1), eq("Payment"), eq(100.5),
            eq("online"), eq("failed"), eq("Insufficient funds."), any(LocalDateTime.class));
    }

	@Test
	@Tag("invalid")
	void invalidAccountIdFormat() {
		paymentRequest.setAccount_id("abc123");

		assertThrows(NumberFormatException.class, () -> {
			transactController.transfer(paymentRequest, session);
		});
	}

	@Test
	@Tag("invalid")
	void invalidPaymentAmountFormat() {
		paymentRequest.setPayment_amount("invalid_amount");

		assertThrows(NumberFormatException.class, () -> {
			transactController.transfer(paymentRequest, session);
		});
	}

	@Test
	@Tag("invalid")
	void nullHttpSession() {
		assertThrows(NullPointerException.class, () -> {
			transactController.transfer(paymentRequest, null);
		});
	}

	@Test
    @Tag("invalid")
    void nullUserInSession() {
        when(session.getAttribute("user")).thenReturn(null);

        assertThrows(NullPointerException.class, () -> {
            transactController.transfer(paymentRequest, session);
        });
    }

	@Test
	@Tag("valid")
	void successfulPaymentWithReferenceField() {
		paymentRequest.setReference("Monthly subscription payment");
		when(session.getAttribute("user")).thenReturn(mockUser);
		when(accountRepository.getAccountBalance(123, 1)).thenReturn(200.0);
		when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.OK, result.getStatusCode());
		Map<String, Object> response = (Map<String, Object>) result.getBody();
		assertEquals("Payment Processed Successfully!", response.get("message"));

		verify(paymentRepository).makePayment(eq(1), eq("John Doe"), eq("9876543210"), eq(100.5),
				eq("Monthly subscription payment"), eq("success"), eq("Payment Processed Successfully!"),
				any(LocalDateTime.class));
	}

	@Test
	@Tag("boundary")
	void largePaymentAmountWithinBalanceLimits() {
		paymentRequest.setPayment_amount("999999.99");
		when(session.getAttribute("user")).thenReturn(mockUser);
		when(accountRepository.getAccountBalance(123, 1)).thenReturn(1500000.0);
		when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.OK, result.getStatusCode());
		Map<String, Object> response = (Map<String, Object>) result.getBody();
		assertEquals("Payment Processed Successfully!", response.get("message"));

		verify(accountRepository).changeAccountsBalanceById(500000.01, 1);
	}

	@Test
	@Tag("invalid")
	void multipleEmptyFieldsCombination() {
		paymentRequest.setBeneficiary("");
		paymentRequest.setAccount_number("");
		paymentRequest.setPayment_amount("");

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
		assertEquals("Beneficiary, account number, account paying from and account payment amount cannot be empty.",
				result.getBody());
	}

	@Test
	@Tag("boundary")
	void paymentAmountExactlyEqualToBalance() {
		paymentRequest.setPayment_amount("100.0");
		when(session.getAttribute("user")).thenReturn(mockUser);
		when(accountRepository.getAccountBalance(123, 1)).thenReturn(100.0);
		when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.OK, result.getStatusCode());
		Map<String, Object> response = (Map<String, Object>) result.getBody();
		assertEquals("Payment Processed Successfully!", response.get("message"));

		verify(accountRepository).changeAccountsBalanceById(0.0, 1);
	}

	@Test
	@Tag("invalid")
	void nullBeneficiaryField() {
		paymentRequest.setBeneficiary(null);

		assertThrows(NullPointerException.class, () -> {
			transactController.transfer(paymentRequest, session);
		});
	}

	@Test
	@Tag("invalid")
	void nullAccountNumberField() {
		paymentRequest.setAccount_number(null);

		assertThrows(NullPointerException.class, () -> {
			transactController.transfer(paymentRequest, session);
		});
	}

	@Test
	@Tag("invalid")
	void nullAccountIdField() {
		paymentRequest.setAccount_id(null);

		assertThrows(NullPointerException.class, () -> {
			transactController.transfer(paymentRequest, session);
		});
	}

	@Test
	@Tag("invalid")
	void nullPaymentAmountField() {
		paymentRequest.setPayment_amount(null);

		assertThrows(NullPointerException.class, () -> {
			transactController.transfer(paymentRequest, session);
		});
	}

	@Test
	@Tag("boundary")
	void verySmallPositivePaymentAmount() {
		paymentRequest.setPayment_amount("0.01");
		when(session.getAttribute("user")).thenReturn(mockUser);
		when(accountRepository.getAccountBalance(123, 1)).thenReturn(1.0);
		when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

		ResponseEntity result = transactController.transfer(paymentRequest, session);

		assertEquals(HttpStatus.OK, result.getStatusCode());
		Map<String, Object> response = (Map<String, Object>) result.getBody();
		assertEquals("Payment Processed Successfully!", response.get("message"));

		verify(accountRepository).changeAccountsBalanceById(0.99, 1);
	}

	@Test
    @Tag("integration")
    void fullPaymentProcessingWorkflow() {
        when(session.getAttribute("user")).thenReturn(mockUser);
        when(accountRepository.getAccountBalance(123, 1)).thenReturn(500.0);
        when(accountRepository.getUserAccountsById(123)).thenReturn(List.of());

        ResponseEntity result = transactController.transfer(paymentRequest, session);

        assertEquals(HttpStatus.OK, result.getStatusCode());
        Map<String, Object> response = (Map<String, Object>) result.getBody();
        assertEquals("Payment Processed Successfully!", response.get("message"));
        assertNotNull(response.get("accounts"));

        verify(accountRepository).getAccountBalance(123, 1);
        verify(accountRepository).changeAccountsBalanceById(399.5, 1);
        verify(accountRepository).getUserAccountsById(123);
        verify(paymentRepository).makePayment(eq(1), eq("John Doe"), eq("9876543210"),
            eq(100.5), eq("Test payment"), eq("success"), eq("Payment Processed Successfully!"), any(LocalDateTime.class));
        verify(transactRepository).logTransaction(eq(1), eq("Payment"), eq(100.5),
            eq("online"), eq("success"), eq("Payment Transaction Successfull"), any(LocalDateTime.class));
    }

}