
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-springboot using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=getAccount_id_77302f79ec
ROOST_METHOD_SIG_HASH=getAccount_id_b8d05339aa

Scenario 1: Returns 0 by default for a newly constructed Account

Details:
  TestName: returnsZeroByDefaultForNewAccount
  Description: Verify that getAccount_id() returns the default primitive int value (0) when a new Account is created and no ID has been explicitly set.

Execution:
  Arrange: Create a new Account instance without setting any fields.
  Act: Call getAccount_id() on the new instance.
  Assert: Use JUnit assertions (e.g., assertEquals) to confirm that the returned value is 0.

Validation:
  The assertion verifies that the primitive int field account_id is initialized to 0 by default in Java.
  This is significant because it confirms predictable behavior for freshly instantiated entities prior to persistence or explicit assignment.

*/

// ********RoostGPT********

package com.beko.DemoBank_v1.models;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class AccountGetAccountIdTest {

	@Test
	@Tag("valid")
	public void testReturnsZeroByDefaultForNewAccount() {
		Account account = new Account();
		int actual = account.getAccount_id();
		assertEquals((int) 0, (int) actual);
	}

}